# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/USER/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-23032-DESKTOP-GRGL43M/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/fft_fpga/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/fft_fpga/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/fft_fpga/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/BF2_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/BF3_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/BF4_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/CU_stage1.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/CU_stage2.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/CU_stage3.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/CU_stage4.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/ShiftREG1_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/ShiftREG2_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/ShiftREG4_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/ShiftREG8_input_MUX.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/Twidle_factor_ROM_stage1.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/Twidle_factor_ROM_stage2.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/Twidle_factor_ROM_stage3.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/butterfly_st1.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/butterfly_st2.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/butterfly_st3.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/butterfly_st4.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/shift_register_1.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/shift_register_2.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/shift_register_4.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/shift_register_8.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/stage1_top.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/stage2_top.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/stage3_top.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/stage4_top.v
  D:/fft_fpga/project_1/project_1.srcs/sources_1/imports/design/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/fft_fpga/project_1/project_1.srcs/constrs_1/imports/fft_fpga/FFT_Basys3_full_constraints.xdc
set_property used_in_implementation false [get_files D:/fft_fpga/project_1/project_1.srcs/constrs_1/imports/fft_fpga/FFT_Basys3_full_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top DIF_R2SDF_top -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DIF_R2SDF_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DIF_R2SDF_top_utilization_synth.rpt -pb DIF_R2SDF_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
